services:
  devcontainer:
    # Image Python : Zensical est un paquet Python
    image: mcr.microsoft.com/devcontainers/python:3-3.14-trixie
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 9090:8080
